enum ORDERS_ACTION_TYPES {
    FETCH_ORDERS_START = 'FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED',
    CLEAR_ORDERS = 'CLEAR_ORDERS',
}

export default ORDERS_ACTION_TYPES;
